apiVersion: apps/v1
kind: Deployment
metadata:
  name: notepad-deployment
  labels: 
    app: notepad
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: notepad
  template:
    metadata: 
      labels:
        app: notepad
    spec:
      containers:
      - name: notepad
        image: mattregojos/app:latest
        ports:
        - containerPort: 8501
